### ISSUE TITLE
[FR] Any way to run default image command?

### ISSUE THREAD

**Issue by rafamel** [binci/binci#100]
Hi, is there any way to run the default command of a given image running as a primary container without making it explicit as a task?

Thanks for the awesome work!

**Comment by Fluidbyte** [comment]
If I'm understanding the question correctly; you can set any scripts you want to be handled as a default command to the `before` in the binci.yml (realize we should improve documentation here):

```yaml
from: node
before: |
  echo "Doing something..."
tasks:
  install: yarn
  ...
```
