### ISSUE TITLE
Docker Desktop 3.3.0 broke binci

### ISSUE THREAD

**Issue by brandonros** [binci/binci#112]
Reproduction:

binci.yml

```
from: registry.hub.docker.com/library/node:lts
services:
  - db:
      from: registry.hub.docker.com/library/postgres:latest
      env:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=example
        - POSTGRES_DB=db
      expose:
        - 5432:5432
tasks:
  hello: echo hello
```

```
$ binci hello
✔ Starting service db
✔ Running Task
‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧
docker: Error response from daemon: Cannot link to a non running container: /bc_db_HDQxOObjp AS /bc_primary_HDQxOObjp/db.
‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧
✖ Command failed
```
