### ISSUE TITLE
DevLab in Windows "Invalid bind mount spec"

### ISSUE THREAD

**Issue by mgleed** [binci/binci#40]
Running Windows 10 Pro, Docker 1.12.5, and DevLab 3.1.1.

I get an error when attempting to start containers with DevLab in Windows (from cmd, git bash, or powershell). I have shared the C: drive.

Here's the output error (personal info substituted with asterisks):
```
> lab install

√ Starting services rabbitmq, postgres
√ Running command: env
‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧
docker: Error response from daemon: Invalid bind mount spec "/C/Users/****/server:C:\\Users\\****\\server": invalid mode: \Users\****\server.
See 'docker run --help'.
‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧‧
× Command failed
```

Here's my config file:
```
from: busybox
services:
  - rabbitmq:
      from: gonkulatorlabs/rabbitmq
      expose:
        - 5672:5672
  - postgres:
        from: kiasaki/alpine-postgres
        env:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=password
          - POSTGRES_DB=dev
        expose:
          - 5432:5432
expose:
  - 9000:9000
quiet: false
forward: true
tasks:
  env: env
  clean: npm run clean
  install: env
  test: npm run test
  lint: npm run lint
  build: npm run build
  start: npm start
  ci: |
    npm run lint 
    npm run test 
    npm run build
```
I can't tell for sure, but it seems like there is a problem with msys path conversion with docker, but I can't (or don't know how to) control what's passed to docker while using DevLab. I know there are some workarounds recommended with docker ([a seemingly related issue](https://github.com/docker/docker/issues/12590)) but I'm not sure how I'd implement these suggestions when DevLab is executing the Docker commands. I'm new to DevLab and Docker, so I apologize if I'm way off the mark here.
