### ISSUE TITLE
Fail to start service

### ISSUE THREAD

**Issue by karneaud** [binci/binci#82]
Tried to do the following

```
services:
  - mysql:
      from: mysql:latest
      ports:
          - '3306:3306'
      volumes:
          - ./mysql:/var/lib/mysql
      environment:
          - MYSQL_ROOT_PASSWORD=aqwe123
      restart: always
  # - nginx:
  #     from: nginx:latest
  #     ports:
  #         - '80:80'
  #     volumes:
  #         - ./nginx:/etc/nginx/conf.d
  #         - ./logs/nginx:/var/log/nginx
  #         - ./wordpress:/var/www/html
  #     links:
  #         - wordpress
  #     restart: always
  - wordpress:
      from: wordpress:4.8.0-php5.6-fpm
      ports:
          - '9000:9000'
      volumes:
          - ./wordpress:/var/www/html
      environment:
          - WORDPRESS_DB_NAME=wpdb
          - WORDPRESS_TABLE_PREFIX=wp_
          - WORDPRESS_DB_HOST=mysql
          - WORDPRESS_DB_PASSWORD=aqwe123
      links:
          - mysql
      restart: always
expose:
   - 8000:8000
   - 3306:3306
   - 9000:9000
from: nginx:latest
ports:
    - '8000:8000'
volumes:
    - ./nginx:/etc/nginx/conf.d
    - ./logs/nginx:/var/log/nginx
    - ./wordpress:/var/www/html
hosts:
  - 192.168.99.100:127.0.0.1
before:
  - echo "before..."
after:
  - echo "after..."
tasks:
  env: env | sort
  # shell: /bin/bash
  # run: "nginx -g daemon off;"

```

kept getting

> Failed to start service wordpress for some reason

While using a docker-compose.yml worked
