### ISSUE TITLE
after hook

### ISSUE THREAD

**Issue by brandonros** [binci/binci#96]
I use Binci to launch a Docker image that exposes a CMD that is a daemon. I have found the need to run shell commands against the container once it has come alive. Since the docker container name is some form of `bc_serviceName_randomLetters`, I'm stuck pretty much using grep/sed/awk to figure out which container I want to attach + run commands to.

Would this be an easy configuration option to add?

```yaml
after:
  containerName:
    - touch magicFile
```
