### ISSUE TITLE
Sharing services

### ISSUE THREAD

**Issue by brandonros** [binci/binci#97]
```
from: foo/node-dev:5
services:
  - vault:
      from: foo/node-vault-dev:latest
      env:
        - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      expose:
        - 8200:8200
  - db:
      from: registry.hub.docker.com/library/postgres:latest
      env:
        - POSTGRES_PASSWORD=example
      expose:
        - 5432:5432
```
It isn't clear in the documentation how to share the exposed 5432 port from the `postgres` service to the `vault` service. Is this currently possible? If so, how?
