### ISSUE TITLE
Service from a Docker file instead of an image

### ISSUE THREAD

**Issue by brandonros** [binci/binci#98]
```
services:
  - db:
      dockerfile: db/Dockerfile
      env:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=example
        - POSTGRES_DB=foo
      expose:
        - 5432:5432
```

Is this not currently possible?
